# Generated by Django 5.2.13 on 2026-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('audio', 'Audio'), ('accessories', 'Accessories'), ('wearables', 'Wearables'), ('peripherals', 'Peripherals'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
